name: WealthLand
favicon: null
layout_spectrum: 0.51769
typography_spectrum: 0.83106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c48635'
    - '#b71218'
    - '#0b1f21'
    - '#ffffff'
    - '#138574'
  brandStrength: 0.05339449783787131
  lightness: 0.8294997059274465
  saturation: 0.8688689665868878
  rhythmicContrast: 1
purpose: []
